### ISSUE TITLE
require $SYS/# Topics

### ISSUE THREAD

**Issue by whatago** [gomqtt/broker#1]
thx again for the great library.
the sys events (such as client connected, disconnect, publish, subscribe) are essential when implementing server side logic.

**Comment by whatago** [comment]
My general thought is adding a localClient into the broker, and then it could keep using the Backend.Publish interface. 
Please correct me :)

**Comment by 256dpi** [comment]
Hi @whatago,

The scope of this package ist implement all necessary specs of the protocol to build a custom MQTT broker. As the `$SYS` events are implementation specific and nowhere defined as a standard the will not be implemented in the reference implementation contained in this package.

The correct way would be to manage a clients `$SYS` subscriptions in the backend and use the `Client.publish` method to forward such events when they occur.

Beware, this package is work in progress and subject to change in the future.
