### ISSUE TITLE
when new client connect, and the clientID is null.

### ISSUE THREAD

**Issue by arden** [gomqtt/broker#3]
```
engine.Logger = func(event broker.LogEvent, client *broker.Client, pkt packet.Packet, msg *packet.Message, err error) {
		if event == broker.MessagePublished {
			println(client.ClientID())  // not null
			atomic.AddInt32(&published, 1)
		} else if event == broker.MessageForwarded {
			atomic.AddInt32(&forwarded, 1)
		} else if event == broker.NewConnection {
			println(client.ClientID())  // is null
		}
	}
```
when a new client connect, and the clientID is null.

**Comment by 256dpi** [comment]
The `NewConnection` log event is dispatched as soon a client has connected. As the `ConnectPacket` has not been processed yet, the `client.ClientID` method will return `""`.

You should use the `Backend` API to implemented any logic that needs exact sate. The `engine.Logger` is really just for getting some quick insight.
