### ISSUE TITLE
this broker could support cluster?

### ISSUE THREAD

**Issue by arden** [gomqtt/broker#6]
this broker could support cluster? or have any plans do it ?

**Comment by 256dpi** [comment]
Cluster support is out of the scope of this package, as this can be implenented in various ways and the MQTT specification does not state anything about clustering.

Explanation: This Go package only implements the MQTT broker semantics. In other words: It is a library to build a MQTT compatible broker. Therefore, the scope of the package is to only abstract the MQTT protocol and provide an API to build any kind of broker on top of it. Thus, it is not really a broker itself. However,  the `MemoryBackend` contained in this package implements enough logic to pass the MQTT specification test, but you should take that Backend only as a starting point to build your own. Please do not run it in a production environment.
